### ISSUE TITLE
07 - My Collections Page

### ISSUE THREAD

**Issue by QuanXuuu** [QuanXuuu/TCGMON-project#10]
## Value proposition
**As a** user ,
**I want to** have a dashboard page,
**so that** I have a better overview of all my collections and add new collections and search for cards.

## Description
![Screenshot from 2023-10-09 15-57-32](https://github.com/QuanXuuu/TCG-project/assets/104725727/55b15d5a-7acc-4700-902d-1805f91cb014)

## Acceptance criteria
- [x] Header with hamburger menu should be displayed
- [x] Collection summary should be displayed
- [x] Button with text "Add new collection" should be displayed and open "Add collection" modal
- [x] Button with text "Search cards" should be displayed and link to search page

## Complexity
Medium

## Tasks
- [x] Create branch
- [x] Create Dashboard page component
- [x] Add Header component into this page
- [x] Add collection summary component into this page
- [x] Add button with text "Add new collection" and open "Add collection" modal
- [x] Add button with text "Search cards" and link to search page
