### ISSUE TITLE
08 - Search by card page

### ISSUE THREAD

**Issue by Bez1887** [QuanXuuu/TCGMON-project#11]
## Value proposition
**As a** user,
**I want to** have a search by card name function,
**so that** i can search single card by name.

## Description
![Bildschirmfoto vom 2023-10-10 09-27-06](https://github.com/QuanXuuu/TCG-project/assets/118745581/ae2a5819-4a27-49f0-9323-244bf086c0cf)

## Acceptance criteria
- [x] Header with logo and hamburger menu inside should be displayed on the top of the page.
- [x] Title should be displayed.
- [x] Button with text "Search by set" should be displayed. 
- [x] Button with text "Search by card" should be displayed in yellow background-color as default.
- [x] Input field with placeholder "Card name" should be displayed.
- [x] Button with text "Show results" should be displayed and link to search result page.

## Complexity
Medium 

## Tasks
- [x] Create branch
- [x] Create search by card page component
- [x] Add header component
- [x] Add two buttons to switch between "Search by set component" and "Search by card component" with useState 
- [x] Create input field with placeholder card name
- [x] Create button with text show results that links to search result page
