### ISSUE TITLE
09 - Search by set Page

### ISSUE THREAD

**Issue by Bez1887** [QuanXuuu/TCGMON-project#12]
## Value proposition
**As a** user,
**I want to** have a search by set name function,
**so that** i can search cards by set name.

## Description
![Bildschirmfoto vom 2023-10-10 09-44-56](https://github.com/QuanXuuu/TCG-project/assets/118745581/d4f70a8f-21d2-479c-8168-3679ec8c07a3)

## Acceptance criteria
- [x] Header with logo and hamburger menu inside should be displayed on the top of the page.
- [x] Title should be displayed.
- [x] Button with text "Search by set" should be displayed in yellow background-color as default.
- [x] Button with text "Search by card" should be displayed.
- [x] Drop down menu with text "Choose set" should be displayed.
- [x] Button with text "Show results" should be displayed and link to search result page.

## Complexity
Medium 

## Tasks
- [x] Create branch
- [x] Create search by set page component
- [x] Add header component
- [x] Add two buttons to switch between "Search by set component" and "Search by card component" with useState 
- [x] Create dropdown menu with text "Choose set"
- [x] Create button with text show results that links to search result page
