### ISSUE TITLE
10 - Search Results Page for Single Cards AND Sealed Products

### ISSUE THREAD

**Issue by Bez1887** [QuanXuuu/TCGMON-project#13]
## Value proposition
**As a** user,
**I want to** have a results page,
**so that** i can find the cards that i'm searching for.

## Description

![Image](https://github.com/QuanXuuu/TCG-project/assets/118744454/f288e362-1a7c-46cd-a9d7-2e2fd66184d1)

![Image](https://github.com/QuanXuuu/TCG-project/assets/118744454/4017e9a3-7021-4620-8e0a-b5e38a38b683)

## Acceptance criteria
- [x] Header with logo and hamburger menu inside should be displayed on the top of the page.
- [x] Button with text "Back to search" and icon should be displayed below header.
- [x] Title with text "Search result for" and underlined search input should be displayed. 
- [x] Number of single cards result should be displayed.
- [x] Number of sealed products should be displayed.
- [x] Search results should be divided by "Single cards" and "Sealed products".
- [ ] Arrows icon for sorting methods should be displayed on the left site of the subtitle with drop down for sorting options. 
- [ ] Filter icon for filtering methods should be displayed on the right site of the subtitle with drop down for filtering options. 
- [x] Search results (Single Card with image and basic information) should be displayed. 

## Complexity
Medium 

## Tasks
- [x] Create branch
- [x] Create search results page component
- [x] Add header component
- [x] Create "Back to search" button with icon and link to search page component
- [x] Create "Search results information" component with title and numbers
- [x] Create "Search result-single card" and "Search result-sealed products" components with image and basic information 
- [ ] Create "Single card/sealed products header" component with title and icons for sorting and filtering methods
- [x] Create "Search result" component and add "Search result-single card" and "Search result-sealed products" components inside
- [x] Add "Single card/sealed products header" component into "Search result" component
