### ISSUE TITLE
11 - Collection Details Page - Data Summary

### ISSUE THREAD

**Issue by Bez1887** [QuanXuuu/TCGMON-project#14]
## Value proposition
**As a** user,
**I want to** have a collection details page,
**so that** i can see the information of my collection.

## Description
![Image](https://github.com/QuanXuuu/TCG-project/assets/104725727/9305ef5f-f290-475c-89af-a89991d708ad)

## Acceptance criteria
- [x] Header with logo and hamburger menu inside should be displayed on the top of the page.
- [x] Button with text "Back to my collections" and icon should be displayed below header.
- [x] Title with "Collection name" should be displayed.
- [x] Button with icon to change the collection name should be displayed on the right side of the collection name.
- [x] Number of single cards should be displayed.
- [x] Number of sealed products should be displayed.
- [x] Total purchase price of collection should be displayed.
- [x] Profit/loss should be displayed in Euro on the right side of total purchase price.
- [x] Total market price of the collection should be displayed.
- [x] Profit/loss should be displayed in percentage on the right side of total market price.
- [x] Button with text "Market Data" should be displayed(optional)
 

## Complexity
Medium

## Tasks
- [x] Create branch
- [x] Create collection details page component 
- [x] Add header component
- [x] Create "Back to my collections" button icon and link to "My collection" component
- [x] Create "Collection details data" component with collection name and edit button with icon
- [x] Display number of single cards inside of "Collection details data" component
- [x] Display number of sealed products inside of "Collection details data" component
- [x] Display total purchase price of collection inside of "Collection details data" component
- [x] Display profit/loss in Euro on the right side of total purchase price
- [x] Display total market price of collection inside of "Collection details data" component
- [x] Display profit/loss in percentage on the right side of total market price
- [x] Create button with text "Market Data"(optional/without link)
