### ISSUE TITLE
11.1 - Collection Details Page - All Single Card Frames Display

### ISSUE THREAD

**Issue by Bez1887** [QuanXuuu/TCGMON-project#15]
## Value proposition
**As a** user ,
**I want to** be able to see all my single cards,
**so that** I have a better overview.

## Description
![Image](https://github.com/QuanXuuu/TCG-project/assets/104725727/c4d61f68-860b-443d-a306-7b1e19f359a0)

## Acceptance criteria
- [x] subtitle with text "Single Cards" should be displayed
- [x] Arrows icon for sorting methods should be displayed on the left site of the subtitle with drop down for sorting options.
- [x] Filter icon for filtering methods should be displayed on the right site of the subtitle with drop down for filtering options.
- [x] Single card set name should be displayed below subtitle.
- [x] Single card with image and basic information should be displayed.
- [x] By default Single cards should be sorted by set names and single card set number.

## Complexity
Medium 

## Tasks
- [x] Create branch
- [x] Create "Collection Details Page - All Single Card Frames Display" component
- [x] Create Subtitle, arrow icon and filter icon for sorting and filtering methods
- [x] Display single card set name above "Collection Details Page - Single Card Frame" component
- [x] Create "Collection Details Page - Single Card Frame" component
- [x] Add Single card image
- [x] Add overlay(card set number) to single car image
- [x] Add Single card name and edit icon
- [x] Add Single card rarity, language, edition, condition/grade, reverse holo status, purchase price, profit/loss in Euro/percentage, market price and portfolio share for position.
- [x] Add button with text "Market Date"(functionality is optional)
