### ISSUE TITLE
12 - Add Card Modal

### ISSUE THREAD

**Issue by Bez1887** [QuanXuuu/TCGMON-project#16]
## Value proposition
**As a** user,
**I want to** have an add new card function,
**so that** i can add new card to my collections.

## Description
![Bildschirmfoto vom 2023-10-10 15-09-46](https://github.com/QuanXuuu/TCG-project/assets/118745581/ab89495d-35ff-44ae-9508-496a6632403d)

## Acceptance criteria
- [x] Close modal button should be displayed. 
- [x] Card name should be displayed. 
- [x] Card image should be displayed below card name.
- [x] Card cycle name should be displayed on the right side. 
- [x] Card set name should be displayed below card cycle name.
- [x] Card set number should be displayed below card set name. 
- [x] Card rarity should be displayed below card set number. 
- [x] Card edition checkbox should be displayed below card image.
- [x] Reverse Holo status checkbox should be displayed to the right of add edition checkbox.
- [x] Card language drop down menu should be displayed below card edition checkbox.
- [x] Card condition drop down menu should be displayed below card language drop down menu.
- [x] Card grade drop down menu should be displayed below card condition drop down menu.
- [x] Card purchase price input field should be displayed below card grade drop down menu.
- [x] Card collection drop down menu should be displayed below card purchase price field.
- [x] Button with text "Add new card" should be displayed. 

## Complexity
High 

## Tasks
- [x] Create branch
- [x] Create "Add card modal" component 
- [x] Create close modal button with icon
- [x] Display card name, image, cycle name, set name, set number and rarity 
- [x] Create checkbox for card edition
- [x] Create checkbox for Reverse Holo status
- [x] Create drop down menu for card language
- [x] Create drop down menu for card condition
- [x] Create drop down menu for card grade
- [x] Create function that disables card grade if value in condition is set and vice versa
- [x] Create input field for card purchase price
- [x] Create drop down menu for collection name
- [x] Create button with text "Add new card" and modal will be closed
