### ISSUE TITLE
13 - Add Collection Modal

### ISSUE THREAD

**Issue by ruben-leon** [QuanXuuu/TCGMON-project#17]
## Value proposition
**As a** user,
**I want to** have a collection modal ,
**so that** I can add a new collection .

## Description
![Bildschirmfoto 2023-10-10 um 15 15 12](https://github.com/QuanXuuu/TCG-project/assets/118744454/29aad433-f228-4c64-8230-b867b8eee7fb)

## Acceptance criteria
- [x] Close modal button should be displayed
- [x] Modal title with text "Create new collection" should be displayed
- [x] Input field with placeholder "Collection name" should be displayed below modal title
- [x] Dropdown menu with placeholder "TCG" should be displayed to select different TCG´s
- [x] Button with text "Create new collection" should be displayed and close the modal

## Complexity
Easy 

## Tasks
- [x] Create branch
- [x] Create "Add Collection Modal" component
- [x] Create close modal button with icon to close the modal
- [x] Create input field for collection name (placeholder: Collection name)
- [x] Create dropdown menu for TCG selection (placeholder: TCG)
- [x] Create button with text "Create new collection" to add new collection to user account and close modal after successfully added
