### ISSUE TITLE
14 - Edit Collection Modal

### ISSUE THREAD

**Issue by ruben-leon** [QuanXuuu/TCGMON-project#18]
## Value proposition
**As a** user,
**I want to**  have a edit collection modal,
**so that** i can update my collections.

## Description
![Bildschirmfoto 2023-10-10 um 15 28 18](https://github.com/QuanXuuu/TCG-project/assets/118744454/5f4b49f2-24b7-4181-9cfc-d778846cf3e7)

## Acceptance criteria
- [x] Close modal button should be displayed
- [x] Modal title with text "Edit collection" should be displayed
- [x] Input field with placeholder "Collection name" should be displayed
- [x] Dropdown menu with placeholder "Pokémon" should be displayed to switch between TCG's (only possible if collection is empty)
- [x] Button with text "Update collection" should be displayed to update the collection
- [x] Button with text "Delete collection" should be displayed to delete the collection (double-check message should pop up)

## Complexity
Easy
 
## Tasks
- [x] Create branch
- [x] Create "Edit Collection Modal" component
- [x] Create close modal button with icon to close the modal
- [x] Create input field for new collection name (placeholder: current collection name)
- [x] If "Collection name" input is activated then text "Collection name" should be visible in upper left corner of the "Collection name" input field (optional)
- [x] Create dropdown menu to switch to a different TCG (only possible if collection is empty / placeholder: Pokémon)
- [x] Create button with text "Update collection" that updates new data for collection and close the modal after successfully updated
- [x] Create button with text "Delete collection" to delete the collection (double-check message should pop up)
- [x] Modal should not be scroll-able
