### ISSUE TITLE
15 - Add Sealed Product Modal

### ISSUE THREAD

**Issue by ruben-leon** [QuanXuuu/TCGMON-project#19]
## Value proposition
**As a** user,
**I want to** to have an Add Sealed Product Modal,
**so that** I can add new sealed products to my collections.

## Description
![Bildschirmfoto 2023-10-10 um 16 14 50](https://github.com/QuanXuuu/TCG-project/assets/118744454/402cd90d-37a3-4771-9cb5-197baa5a2334)

## Acceptance criteria
- [x] Close modal button should be displayed
- [x] Sealed product name should be displayed
- [x] Sealed product image should be displayed below product name.
- [x] Sealed product cycle name should be displayed on the right side. 
- [x] Sealed product set code should be displayed below product cycle name.
- [x] Sealed product category should be displayed below sealed product set code. 
- [x] Sealed product edition checkbox should be displayed below sealed product image.
- [x] Sealed product language drop down menu should be displayed below product edition checkbox.
- [x] Sealed product purchase price input field should be displayed below sealed product language drop down menu.
- [x] Sealed product amount input field should be displayed 
- [x] Collection drop down menu should be displayed below sealed product amount input field.
- [x] Button with text "Add new product" should be displayed. 

## Complexity
Medium 

## Tasks
- [x] Create branch
- [x] Create "Add Sealed Product Modal" component :)
- [x] Create close modal button with icon
- [x] Display "Sealed products" name, image, cycle name, set code and category
- [x] Create checkbox for sealed product edition
- [x] Create dropdown menu for sealed product language
- [x] Create input field for sealed product amount
- [x] Create dropdown for collection
- [x] Create button with text "Add new product" and modal will be closed when successfully added
