### ISSUE TITLE
01 - Landing Page

### ISSUE THREAD

**Issue by QuanXuuu** [QuanXuuu/TCGMON-project#2]
## Value proposition

**As a** user,
**I want to** have a landing page,
**so that** I can register or login to use the app.

## Description
![Screenshot from 2023-10-09 13-28-10](https://github.com/QuanXuuu/TCG-project/assets/104725727/1dcb01f1-10c2-4ee9-b6b9-d4ac9534e6fd)

## Acceptance criteria
- [x] App logo should be displayed
- [x] Main images should be displayed in the middle of the page
- [x] Two buttons should be displayed in two rows
- [x] Login button should bring us to Login route
- [x] Register button should bring us to Register route

## Complexity
Easy

## Tasks
- [x] Create branch
- [x] Create landing page component
- [x] Create logo component
- [x] Create button component
- [x] Create two buttons for login and register 
- [x] Create connection to the routers
