### ISSUE TITLE
11.2 - Collection Details Page - All Sealed Products Card Frames Display

### ISSUE THREAD

**Issue by QuanXuuu** [QuanXuuu/TCGMON-project#20]
## Value proposition
**As a** user ,
**I want to** be able to see all my sealed products,
**so that** I have a better overview.

## Description
![Screenshot from 2023-10-11 09-41-26](https://github.com/QuanXuuu/TCG-project/assets/104725727/621787a0-274f-4d23-a21b-1b123c48802c)

## Acceptance criteria
- [x] subtitle with text "Sealed Products" should be displayed
- [x] Arrows icon for sorting methods should be displayed on the left site of the subtitle with drop down for sorting options.
- [x] Filter icon for filtering methods should be displayed on the right site of the subtitle with drop down for filtering options.
- [x] Sealed products set name should be displayed below subtitle
- [x] Sealed products with image and basic information should be displayed.
- [x] By default Sealed products should be sorted by set names and Sealed products category.

## Complexity
Medium

## Tasks
- [x] Create branch
- [x] Create "Collection Details Page - All Sealed Products Card Frames Display" component
- [x] Create Subtitle, arrow icon and filter icon for sorting and filtering methods
- [x] Display Sealed product set name above "Collection Details Page - Sealed Product Card Frame" component
- [x] Create "Collection Details Page - Sealed Product Card Frame" component
- [x] Add Sealed products image
- [x] Add overlay(amount) to sealed product image
- [x] Add Sealed products name and edit icon
- [x] Add Sealed products set code, language, edition, purchase, profit/loss in Euro/percentage, market price, portfolio share and total market price for position.
- [x] Add button with text "Market Date"(functionality is optional)
