### ISSUE TITLE
02 - Register Page

### ISSUE THREAD

**Issue by QuanXuuu** [QuanXuuu/TCGMON-project#3]
## Value proposition

**As a** user,
**I want to** have a register page,
**so that** I can register as a user and start using the app.

## Description
![Screenshot from 2023-10-09 14-03-10](https://github.com/QuanXuuu/TCG-project/assets/104725727/a7b76190-c9eb-4051-8584-d7ac1875fdf1)

## Acceptance criteria
- [x] App logo should be displayed
- [x] Headline should be displayed
- [x] Two input fields for email address and password should be displayed
- [x] Register button should be displayed
- [x] Login button should be displayed and link to the login page
 
## Complexity
Medium 

## Tasks
- [x] Create branch
- [x] Create register page component
- [x] Create register form component
- [x] Create login page component
- [x] Register button and login button should link to login page
