### ISSUE TITLE
03 - Login Page

### ISSUE THREAD

**Issue by QuanXuuu** [QuanXuuu/TCGMON-project#4]
## Value proposition
**As a** user ,
**I want to** have a login page,
**so that** I can login and start using the app.

## Description
![Screenshot from 2023-10-09 14-19-27](https://github.com/QuanXuuu/TCG-project/assets/104725727/0248cdd6-8ddb-47b9-8d92-7395e0587398)

## Acceptance criteria
- [x] App logo should be displayed
- [x] Headline with text "Welcome back" should be displayed
- [x] Two input fields for email address and password should be displayed
- [x] Button with text "Forgot your password" should be displayed (without function)
- [x] Login button should be displayed
- [x] Register button should be displayed and link to the register page

## Complexity
Medium 

## Tasks
- [x] Create branch
- [x] Create Login page component
- [x] Create Login form component
- [x] Create button with text "Forgot your password" but without function (low priority)
- [x] Register button should link to register page
- [x] Login button should link to Dashboard after successful logged in
