### ISSUE TITLE
04 - Header

### ISSUE THREAD

**Issue by QuanXuuu** [QuanXuuu/TCGMON-project#5]
## Value proposition
**As a** user ,
**I want to** have a header,
**so that** I can navigate in the app.

## Description
![Screenshot from 2023-10-09 14-35-37](https://github.com/QuanXuuu/TCG-project/assets/104725727/158fe936-2c3b-4da3-b12d-9299937cdb16)

## Acceptance criteria
- [x] App-logo should be displayed
- [x] Hamburger menu should be display and stay at the right side

## Complexity
Easy

## Tasks
- [x] Create branch
- [x] Create header component
- [x] Create hamburger menu with navigate options
