### ISSUE TITLE
XX - unsorted Tasks

### ISSUE THREAD

**Issue by juse122** [QuanXuuu/TCGMON-project#56]
## Value proposition
**As a** user ,
**I want to** feel that every detail was handled by the dev team,
**so that** I can have a seamless app experience.

## Description
All unsorted / unrefined tasks go here

## Acceptance criteria
- [ ] All tasks are refined and project is finished

## Complexity
Easy - Hard

## Tasks
- [ ] Prettier: compare all our settings so that the reformatting is uniform
- [ ] Agree on specific CSS class, id and code conventions
- [ ] 404 Error page
- [ ] Back to top button or fixed header?
- [ ] How to delete localStorage after certain time period?
- [x] Fix price information edge case handling, e.g. no price available for card/product
- [ ] Find better implementation solution for modal toggle code
- [x] Protected routes when user is not logged in
- [ ] Use real Pokémon API key in all external fetch requests
- [x] Popup messages for all dynamic success and error events (Error Modals: Create collection duplicate, Edit collection duplicate, usw)
- [x] Verifying and sanitizing all inputs
- [x] Unify input value format for database (all lowercase)
- [ ] Collection details - filter and sort functionality
- [ ] Search results - filter and sort functionality
- [ ] Footer subpages
- [ ] Move search functionality to backend
- [x] Implement dynamic user document usage
- [x] Fix navigation links so that they work even if user is already on target URL
- [x] Modify pages so that refreshing the browser does not break any functionality
- [ ] Create a Storybook (https://storybook.js.org) documentation and refactor the whole project :(

## Future ideas
- [ ] Reverse all filter functions with backwards filter
- [ ] Improve error notification logic to allow for specific error messages
- [ ] Page loading spinner animation until page is fully loaded
- [ ] Spinner animation inside button on modals to show progress of triggered operation, and only close modal after completion
- [ ] Symbol on each search results that shows if the card/product is already part of a collection
- [ ] Ability to arrange collection summaries
- [ ] Alert message if market price changes by x% in a certain time period
- [ ] Button link to Cardmarket in each card/product entry, with URL dynamically created from card condition info (might be prerequisite for cardmarket API access?)
- [ ] Market data modal with historical price information for each collection/card/product
- [ ] Top5 winners/losers component for collection details page to track sudden price changes
- [ ] Separate "Desktop Mode" in which you can edit entire search results on one page at the same time in a large table
- [ ] For Desktop Mode: Report price error button at the end of each row, for giving feedback about price calculation algorithm (too high/low + comment)
- [ ] Start tracking historical price data in a new "card" or "product" document whenever a card/product gets added to any collection --> delete entry when card/product is not included in any collection anymore
