### ISSUE TITLE
05 - Hamburger Menu

### ISSUE THREAD

**Issue by QuanXuuu** [QuanXuuu/TCGMON-project#6]
## Value proposition
**As a** user ,
**I want to** have a hamburger menu at the top of the app,
**so that** I can easily navigate.

## Description
![Screenshot from 2023-10-09 14-48-02](https://github.com/QuanXuuu/TCG-project/assets/104725727/1467c444-5758-4c62-ab0f-b7f46c19498c)

## Acceptance criteria
- [x] Hamburger menu logo should be displayed
- [x] After click the hamburger, navigation options like "Search, Dashboard and logout" should be toggled

## Complexity
Medium

## Tasks
- [x] Create branch
- [x] Create hamburger component
- [x] Create navigation page component
- [x] Create navigation options and link to the pages accordingly
- [x] Create footer
