### ISSUE TITLE
06 - Collection Summary

### ISSUE THREAD

**Issue by QuanXuuu** [QuanXuuu/TCGMON-project#7]
## Value proposition
**As a** user ,
**I want to** see all my collections,
**so that** I can have a better overview.

## Description
![Image](https://github.com/QuanXuuu/TCG-project/assets/104725727/8719b0ed-effa-43fa-b85c-f8d0bf5e8ece)

## Acceptance criteria
- [x] Page title "My collections" should be displayed
- [x] Each collection should be displayed as a card
- [x] Collection name should be displayed
- [x] Number of cards in this collection should be displayed
- [x] Number of sealed products in this collection should be displayed
- [x] Total price of the cards in this collection should be displayed
- [x] Button with text "view collection" should be displayed
- [x] User can swipe between collections
- [x] After click the view collection button, user should be navigated to the collection details page

## Complexity
Medium

## Tasks
- [x] Create branch
- [x] Create collection card component
- [x] Create canvas component for collections
- [x] Create information details for the collection card with icon
- [x] Create "View collection button" 
- [x] Create link for "View collection button"
