### ISSUE TITLE
02.1 - Register Page Error Modal

### ISSUE THREAD

**Issue by QuanXuuu** [QuanXuuu/TCGMON-project#8]
## Value proposition
**As a** user ,
**I want to** have a reminder when I put invalid register information,
**so that** I can try again to register with correct information.

## Description
![Screenshot from 2023-10-09 15-45-42](https://github.com/QuanXuuu/TCG-project/assets/104725727/b2a5bc54-2129-45fe-ab46-ce65d72d8211)

## Acceptance criteria
- [x] Error modal should be displayed between app-logo and title text if email is invalid
- [x] Error modal should disappear after 5 seconds

## Complexity
Easy

## Tasks
- [x] Create branch
- [x] Create Error modal with text "Invalid email address"
- [x] Create setTimeOut to ensure Error modal disappears after 5 seconds
