### ISSUE TITLE
03.1 - Login Page Error Modal

### ISSUE THREAD

**Issue by QuanXuuu** [QuanXuuu/TCGMON-project#9]
## Value proposition
**As a** user ,
**I want to** have a reminder when I put wrong login information,
**so that** I can try again to login with correct information.

## Description
![Screenshot from 2023-10-09 15-50-10](https://github.com/QuanXuuu/TCG-project/assets/104725727/17ce9f95-e494-4666-bd80-97930f491acd)

## Acceptance criteria
- [x] Error modal should be displayed between app-logo and title text if login information is wrong
- [x] Error modal should disappear after 5 seconds

## Complexity
Easy

## Tasks
- [x] Create branch
- [x] Create Error modal with text "Wrong username and/or password"
- [x] Create setTimeOut to ensure Error modal disappears after 5 seconds
